name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Go Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install make (Windows)
      if: runner.os == 'Windows'
      run: choco install -y make mingw

    - name: Generate Code
      if: runner.os == 'Linux'
      run: make admin && make client

    - name: Check
      run: make check
      env:
        ATRIUM_API_KEY: ${{ secrets.ATRIUM_API_KEY }}
        ATRIUM_CLIENT_ID: ${{ secrets.ATRIUM_CLIENT_ID }}
        PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
        PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
        PLAID_ENVIRONMENT: "sandbox"
        PLAID_CLIENT_NAME: "test"

    - name: Upload Code Coverage
      if: runner.os == 'Linux'
      run: bash <(curl -s https://codecov.io/bash)

    - name: Docker Build
      if: runner.os == 'Linux'
      run: make docker && make test-integration && make clean-integration
